# Generated by Django 2.0.6 on 2018-06-14 04:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='party_Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Party', primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.TextField(max_length=200, null=True)),
                ('gstin', models.CharField(max_length=15, unique=True, verbose_name='GSTIN')),
                ('Contact', models.IntegerField(max_length=11, null=True)),
            ],
        ),
    ]
