# Generated by Django 2.0.6 on 2020-05-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_ledger',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
