# Generated by Django 2.0.6 on 2018-06-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_ledger',
            name='Contact',
            field=models.IntegerField(null=True),
        ),
    ]
