# Generated by Django 2.0.6 on 2018-06-18 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20180614_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_ledger',
            name='Contact',
            field=models.CharField(blank=True, default=999999999, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
