# Generated by Django 2.0.6 on 2020-05-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0001_initial'),
        ('stocks', '0003_auto_20200513_1841'),
        ('party', '0002_auto_20200509_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='gate_pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passNo', models.IntegerField()),
                ('date', models.DateField()),
                ('driver_name', models.CharField(max_length=30, null=True)),
                ('Auto_No', models.CharField(max_length=20, null=True)),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('bill_no', models.CharField(max_length=40)),
                ('bags', models.IntegerField()),
                ('boxes', models.IntegerField()),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='party.party_Ledger')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodity.Commodity')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.Stocks')),
            ],
        ),
    ]
