# Generated by Django 2.0.6 on 2018-06-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate_pass',
            name='Address',
        ),
    ]
