# Generated by Django 2.0.6 on 2018-06-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0002_remove_gate_pass_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_pass',
            name='lot',
            field=models.IntegerField(),
        ),
    ]
