# Generated by Django 2.0.6 on 2018-06-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0003_auto_20180630_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_pass',
            name='commodity',
            field=models.CharField(help_text='Enter a commodity', max_length=200),
        ),
    ]
