# Generated by Django 2.0.6 on 2018-06-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0004_auto_20180630_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_pass',
            name='passNo',
            field=models.IntegerField(),
        ),
    ]
