# Generated by Django 2.0.6 on 2020-05-05 15:25

from django.db import migrations, models
import django.db.models.deletion
import stocks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.IntegerField(default=stocks.models.Stocks.number, unique=True)),
                ('date', models.DateField()),
                ('begs', models.IntegerField(default=0)),
                ('boxes', models.IntegerField(default=0)),
                ('rem_beg', models.IntegerField(default=0)),
                ('rem_box', models.IntegerField(default=0)),
                ('remarks', models.TextField(max_length=200, null=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party_Ledger')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Commodity')),
            ],
        ),
    ]
