# Generated by Django 2.0.6 on 2018-06-15 03:50

import commodity.models
from django.db import migrations, models
import party.models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='Name',
            field=models.CharField(max_length=200, verbose_name=party.models.party_Ledger),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='commodity',
            field=models.CharField(max_length=200, verbose_name=commodity.models.Commodity),
        ),
    ]
