# Generated by Django 2.0.6 on 2020-05-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='party.party_Ledger'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodity.Commodity'),
        ),
    ]
