# Generated by Django 2.0.6 on 2020-05-13 13:11

from django.db import migrations, models
import stocks.models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20200505_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='id',
        ),
        migrations.AlterField(
            model_name='stocks',
            name='lot',
            field=models.IntegerField(default=stocks.models.Stocks.number, primary_key=True, serialize=False),
        ),
    ]
