# Generated by Django 2.0.6 on 2018-06-15 03:51

from django.db import migrations, models
import stocks.models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20180615_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='commodity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='lot',
            field=models.IntegerField(default=stocks.models.Stocks.number, unique=True),
        ),
    ]
