# Generated by Django 2.0.6 on 2018-06-16 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20180615_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party_Ledger'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Commodity'),
        ),
    ]
