# Generated by Django 2.0.6 on 2018-06-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20180616_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='begs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='boxes',
            field=models.IntegerField(default=0),
        ),
    ]
