# Generated by Django 2.0.6 on 2018-06-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20180619_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='remarks',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
