# Generated by Django 2.0.6 on 2018-10-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20180619_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='rem_beg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='rem_box',
            field=models.IntegerField(default=0),
        ),
    ]
